name: Update Contribution Record on DNS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-dns-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run DNS updater
        env:
          CONTRIBUTIONS_TOKEN: ${{ secrets.CONTRIBUTIONS_TOKEN }}
        run: go run ./cmd/dns-updater
